version: '3'
services:
  db:
    image: mysql:latest
    container_name: crud_mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=crud_db
    ports:
      - 3307:3306
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql